# Generated by Django 4.0.5 on 2022-06-22 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('tank', 'Танки'), ('hial', 'Хилы'), ('dd', 'ДД'), ('torgashi', 'Торговцы'), ('gildmaster', 'Гилдмастеры'), ('quiest', 'Квестигры'), ('kuznetz', 'Кузнецы'), ('kojevnik', 'Кожевники'), ('zelpovar', 'Зельевары'), ('masterzak', 'Мастера заклинаний')], default='tank', max_length=10)),
                ('upload_image', models.ImageField(blank=True, upload_to='upload_image/')),
                ('upload_file', models.FileField(blank=True, upload_to='upload_file/')),
                ('sum_comment', models.SmallIntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_dateCreation', models.DateField(auto_now_add=True)),
                ('comment_text', models.TextField()),
                ('comment_status', models.BooleanField(default=False)),
                ('comment_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.post')),
            ],
        ),
    ]
